displayName: Check request headers plugin
type: middleware

import: github.com/dkijkuit/checkheadersplugin

summary: '[Demo] Check request headers'

testData:
  headers:
    - header:
      name: "HEADER_1"
      value: "VALUE_1"
    - name: "HEADER_2"
      value: "VALUE_2"
    - header:
      name: "HEADER_3"
      value: "VALUE_3"
      required: false