# Dynamic configuration

http:
  routers:
    my-router:
      rule: Path(`/whoami`)
      service: service-whoami
      entryPoints:
        - http
      middlewares:
        - checkheaders

  services:
   service-whoami:
      loadBalancer:
        servers:
          - url: http://127.0.0.1:5000
  
  middlewares:
    checkheaders:
      plugin:
        dev:
          headers:
            - header:
              name: "HEADER_1"
              values: "VALUE_1"
            - name: "HEADER_2"
              values: "VALUE_2"
            - header:
              name: "HEADER_3"
              values: "VALUE_3"
              required: false
            - header:
              name: "HEADER_4"
              values: "LUE_4"
              contains: true
              required: true